name = "nvpair"
version = "1.0.0"

description = "Pure Gleam native and XDR packed nvpair codec for ZFS"
licences = ["BSD-2-Clause"]
repository = { type = "github", user = "ryan-moeller", repo = "gleam-nvpair" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
iv = ">= 1.4.2 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.6 and < 2.0.0"
file_streams = ">= 2.0.0 and < 3.0.0"
